In [17]:
import torch

In [14]:
x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.FloatTensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0] ])

W = torch.zeros(4, 3, requires_grad=True)
b = torch.zeros(1, 3, requires_grad=True)

#optimizer 사용
optimizer = torch.optim.Adam([W,b], lr=0.1)

for epoch in range(3001):
  hypothesis = torch.softmax(torch.mm(x_train, W)+b, dim=1)
  cost = -torch.mean(torch.sum(y_train * torch.log(hypothesis), dim=1))

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 1.098612
epoch: 300, cost: 0.105262
epoch: 600, cost: 0.042634
epoch: 900, cost: 0.023111
epoch: 1200, cost: 0.014479
epoch: 1500, cost: 0.009879
epoch: 1800, cost: 0.007124
epoch: 2100, cost: 0.005338
epoch: 2400, cost: 0.004113
epoch: 2700, cost: 0.003236
epoch: 3000, cost: 0.002588


In [6]:
# 새로운 x값이 주어질 때 y값 예측해보기
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
test_all = torch.softmax(torch.mm(x_test, W)+b, dim=1)
print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])
tensor([0, 0, 0])


In [16]:
import torch.nn.functional as F
import torch.nn as nn

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.LongTensor([2,2,2,1,1,1,0,0])

#nn.Linear, optimizer 사용
model = nn.Linear(4,3)
optimizer = torch.optim.Adam(model.parameters(),lr=1)

for epoch in range(3001):
  z = model(x_train)
  #F.cross_entropy 사용
  cost = F.cross_entropy(z, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 2.621607
epoch: 300, cost: 0.026596
epoch: 600, cost: 0.010134
epoch: 900, cost: 0.005409
epoch: 1200, cost: 0.003376
epoch: 1500, cost: 0.002303
epoch: 1800, cost: 0.001662
epoch: 2100, cost: 0.001246
epoch: 2400, cost: 0.000961
epoch: 2700, cost: 0.000757
epoch: 3000, cost: 0.000606


In [23]:
import numpy as np
from sklearn.linear_model import LogisticRegression

x_train = np.array([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],[1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = np.array([ 2, 2, 2, 1, 1, 1, 0, 0 ])

model = LogisticRegression()
model.fit(x_train, y_train)

print(model.coef_, model.intercept_)

# 새로운 x값이 주어질 때 y값 예측해보기
x_test = [[1,11,10,9], [1,3,4,3], [1,1,0,1]]
test_result = model.predict(x_test) 
print(test_result)

[[-0.08836656  0.36653331  0.68248281  0.56089548]
 [ 0.09655093 -0.03183774  0.04266696  0.07421238]
 [-0.00818438 -0.33469557 -0.72514977 -0.63510785]] [-7.99451056  0.60609984  7.38841073]
[0 2 2]
